name: Deploy SAM Application for develop

on:
  push:
    branches:
      - develop
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  prod-deploy:
    runs-on: ubuntu-latest
    environment: production
      - uses: actions/checkout@v3
    
      - name: Deploy SAM Application
        uses: ./.github/actions/sam-deploy # ローカルアクションの場合
        with:
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1
          stack-name: lambda-cicd-stack
          alias-name: Test

  prod-switchover:
    needs: prod-deploy
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1

      - name: Update Prod Alias
        run: |
          # 前のジョブから関数名とバージョンを取得
          FUNCTION_NAME="${{ needs.prod-deploy.outputs.function_name }}"
          VERSION="${{ needs.prod-deploy.outputs.version }}"

          if [ -z "$FUNCTION_NAME" ] || [ -z "$VERSION" ]; then
            echo "関数名またはバージョンが取得できませんでした。CloudFormationスタックから再取得します。"
            
            FUNCTION_NAME=$(aws cloudformation describe-stacks --stack-name lambda-cicd-stack --query "Stacks[0].Outputs[?OutputKey=='HelloWorldFunction'].OutputValue" --output text)
            
            if [[ "$FUNCTION_NAME" == arn:aws:lambda:* ]]; then
              FUNCTION_NAME=$(echo "$FUNCTION_NAME" | awk -F: '{print $7}')
            fi
            
            # 最新のバージョンを取得
            VERSION=$(aws lambda list-versions-by-function --function-name $FUNCTION_NAME --query "Versions[-1].Version" --output text)
          fi

          echo "Lambda関数名: $FUNCTION_NAME"
          echo "デプロイするバージョン: $VERSION"

          # Prodエイリアスが既に存在するか確認
          if aws lambda get-alias --function-name $FUNCTION_NAME --name Prod &> /dev/null; then
            # エイリアスが存在する場合は更新
            aws lambda update-alias --function-name $FUNCTION_NAME --name Prod --function-version $VERSION
            echo "Prodエイリアスをバージョン $VERSION に更新しました"
          else
            # エイリアスが存在しない場合は作成
            aws lambda create-alias --function-name $FUNCTION_NAME --name Prod --function-version $VERSION
            echo "Prodエイリアスをバージョン $VERSION で作成しました"
          fi
